using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;

namespace MongoDB
{
    /// <summary>
    /// Class for the Person Model
    /// </summary>

    public class PersonModel
    {
        [BsonId]                                        //Make sure this is a genuine _Id for the PersonModel tabel
        public Guid Id { get; set; }                    //Guid auto-generated by MonoDB when record is non-existant
        [BsonElement("FirstName")]
        public string FirstName { get; set; }
        [BsonElement("LastName")]
        public string LastName { get; set; }
        [BsonElement("IsAdmin")]
        public bool IsAdmin { get; set; } = false;      //standard admin is false unless otherwise specified

    }

    
}
